#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then
    if command -v sudo &> /dev/null; then
        echo "Reload with sudo..."
        exec sudo bash "$0" "$@"
    else
        echo "Need root acess (su -)."
        exit 1
    fi
fi

set -e

echo "--- 1. Update & Download base utilities ---"
apt update && apt install -y sudo curl ufw nano

echo "--- 2. Settings for UFW ---"
ufw allow ssh
ufw allow 2222/tcp
ufw allow 443/tcp
ufw default deny incoming
ufw default allow outgoing
ufw --force enable

echo "--- 3. Enable BBR ---"
if ! grep -q "net.core.default_qdisc=fq" /etc/sysctl.conf; then
    echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
    echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
    sysctl -p
fi

echo "--- 4. WARP Installatiom ---"
printf "1" | sudo bash -c "$(curl -sL https://raw.githubusercontent.com/xxphantom/docker-warp-native/main/install.sh)"

echo "--- 5. Docker Installation  ---"
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com | sh
fi

echo "--- 6. Install RemnaNode ---"
mkdir -p /opt/remnanode
cd /opt/remnanode

echo "-------------------------------------------------------"
echo "Nano is opening soon"
echo "1. Get config"
echo "2. Ctrl+O, Enter"
echo "3. Ctrl+X"
echo "-------------------------------------------------------"
sleep 2


nano docker-compose.yml < /dev/tty

echo "--- 7. Start Docker Compose ---"
docker compose up -d

echo "--- 8. Logs (Ctrl + C for exit) ---"
docker compose logs -f -t
